version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Automatically merge pull requests once it passes all checks"
    validate:
      - do: description
        no_empty:
          enabled: true
          message: 'Description cannot be empty!'
