version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Description checks"
    validate:
      - do: description
        no_empty:
          enabled: true
          message: 'Description cannot be empty!'
        must_include:
          regex: '\[x\] ?I know what I am doing|\[x\] ?This is bullshit'
          regex_flag: 'i'
          message: >
            Check the checkbox, bitch!
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Title checks"
    validate:
      - do: title
          begins_with:
            match: ['TRIVIAL', 'FIX', 'FEATURE', 'CHORE', 'DOC']
            message: 'You have to prefix title with TRIVIAL, FIX, FEATURE, CHORE or DOC'
          jira:
            regex: '([A-Z]{2,6}-\d+)|(NOJIRA)'
            regex_flag: none
            message: 'Add JIRA ticket into the description'
